name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: [1.0.5, 1.1.3, 1.2.3, 1.3.3, 1.4.6]
    name: Deno ${{ matrix.deno }}
    steps:
      - uses: actions/checkout@master
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: Test
        run: deno test --allow-net
